### ISSUE TITLE
Constitution file. upon restart should it be read from db or file ?

### ISSUE THREAD

**Issue by davetejas** [Lamden/cilantro-enterprise#105]
**Describe the bug**

Current imp reads constitution file from file, this means we need way to regularly dump state upon any changes to  conf.CONSTITUTION_FILE. that infra is absent as of now.

if conf.RESET_DB:
    ContractingClient().raw_driver.flush()

seed_vkbook(conf.CONSTITUTION_FILE)

**Comment by StuartFarmer** [comment]
We should go away from conf altogether in my opinion and pass the argument only at the start of the node. We also don't need to dump constitution to state after the network initially is up. New nodes that are just starting also need to dump constitution to state the first time they start.
