### ISSUE TITLE
New directory structure

### ISSUE THREAD

**Issue by davetejas** [Lamden/cilantro-enterprise#64]
TOP level Dir structure

- src   // Main release 
  - cilantro_ee
     - main.py ---> cli and dynamic constitution
  - setup.py
  - requirement.txt

- OPS    // Devops stuff
  - docker
  - scripts

- tools    --> DELETE
- tests
- scripts
- Readme
-license
-docs

**Comment by OO7Joe** [comment]
@davetejas

**Comment by davetejas** [comment]
Cilantro_ee 

1 Config
    - main.py
 
2 Core
    - audit
    - messages
    - crypto
    - containers
    - sockets
    - sockets
    - utils 
        - logger

4 node 
   - master 
   - delegate

3 Services
     - storage
     - multithread seneca client
     - webserver
      - block minter
      - scheduler
      - overlay
      - lookup/explorer

2 Contracts

2 Governance

1 __main__.py/cli/scripts
