### ISSUE TITLE
add_sub_block in block_manager.SubBlocks seems broken.

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/cilantro-enterprise#82]
```python
    def add_sub_block(self, sub_block, fut):
        sb_idx = sub_block.subBlockIdx % NUM_SB_PER_BLOCK

        if sb_idx in self.sbs:
            # todo log it as an issue
            pass

        self.sbs[sb_idx] = sub_block

        self.futures.append(fut)
```

Why is this occurring? Is there a situation where a subBlockIdx is ever greater than the NUM_SB_PER_BLOCK and we want to process it anyway? If a sbb with value 100 comes in before 0, does it take precedence? If not, then we should just ignore any sbi's greater than NUM_SB_PER_BLOCK like so:

```python
    def add_sub_block(self, sub_block, fut):
        if sub_block.subBlockIdx < NUM_SB_PER_BLOCK and not sb_idx in self.sbs:
            sb_idx = sub_block.subBlockIdx % NUM_SB_PER_BLOCK
            self.sbs[sb_idx] = sub_block

            self.futures.append(fut)
```

**Comment by raghupc** [comment]
No, this is related to the fact that number of sub-blocks we use to make a block may not be equal to the total number of sub-blocks. For eg, if we have 8 sub-blocks and we limit 4 sub-blocks per block, then there will be two blocks each covering 4 sub-blocks. At this level, irrespective of sub-block index, we want to put them in the array from 0 - 3. This will help to handle the logic uniformly.

**Comment by StuartFarmer** [comment]
So if we have 8 subblocks and 4 per block, each time the masternodes send their work to the delegates, 2 blocks of transactions will be minted?
